#! zsh
ITERM2_DIR=$XDG_CACHE_HOME/zsh/iterm2
if [[ ! -r $ITERM2_DIR/startup.zsh ]]; then
	mkdir -p $ITERM2_DIR/bin
	curl -fLo $ITERM2_DIR/startup.zsh https://iterm2.com/misc/zsh_startup.in 
	for cmd in imgcat it2dl; do
		curl -fLo $ITERM2_DIR/bin/$cmd https://iterm2.com/$cmd 
		chmod u+x $ITERM2_DIR/bin/$cmd 
	done
fi
source $ITERM2_DIR/startup.zsh
path+=($ITERM2_DIR/bin)
